import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Intro to <a href="https://nextjs.org">Next.js!</a>
        </h1>
          <h2 className={styles.footer}>
            hello
          </h2>
        <Link href = "/listings" >See all listings</Link>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.youtube.com/watch?v=dQw4w9WgXcQ"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by William Sauvageau and Duncan Volk
        </a>
      </footer>
    </div>
  )
}

export default Home
